# SagaGuild 配置文件

# 数据库设置
database:
  # 数据库文件路径
  path: "plugins/SagaGuild/database.db"

# 公会设置
guild:
  # 创建公会所需金额
  creation-cost: 1000
  # 公会名称最小长度
  min-name-length: 3
  # 公会名称最大长度
  max-name-length: 16
  # 公会标签最小长度
  min-tag-length: 2
  # 公会标签最大长度
  max-tag-length: 5
  # 公会描述最大长度
  max-description-length: 100
  # 公会公告最大长度
  max-announcement-length: 200

# 领地设置
land:
  # 每个公会最大领地数量
  max-claims: 10
  # 领地声明费用
  claim-cost: 500
  # 领地保护范围（方块）
  protection-radius: 16

# 公会等级设置
levels:
  # 基础升级经验需求
  base-exp: 1000
  # 每级增加的经验需求
  exp-increase: 500
  # 最大公会等级
  max-level: 10
  # 每个等级的最大成员数量
  max-members-per-level:
    1: 10   # 1级公会最多10名成员
    2: 15   # 2级公会最多15名成员
    3: 20   # 3级公会最多20名成员
    4: 25   # 4级公会最多25名成员
    5: 30   # 5级公会最多30名成员
    6: 40   # 6级公会最多40名成员
    7: 50   # 7级公会最多50名成员
    8: 60   # 8级公会最多60名成员
    9: 80   # 9级公会最多80名成员
    10: 100 # 10级公会最多100名成员

# 公会战设置
war:
  # 公会战持续时间（分钟）
  duration: 30
  # 公会战准备时间（分钟）
  preparation-time: 5
  # 公会战最小参与人数
  min-participants: 3

# 公会银行设置
bank:
  # 是否启用公会银行
  enabled: true
  # 初始银行容量
  initial-capacity: 10000
  # 每级增加的银行容量
  capacity-increase: 5000

# 公会聊天设置
chat:
  # 是否启用公会聊天
  enabled: true
  # 公会聊天格式
  format: "&8[&b公会&8] &f{player}: &7{message}"
  # 联盟聊天格式
  ally-format: "&8[&d联盟&8] &f{player}: &7{message}"

# 调试模式
debug: false
